### ISSUE TITLE
Mycelium supports BIP 70

### ISSUE THREAD

**Issue by cjr-roland** [bitpay/bitpay-website#81]
Since its latest update (06/10/2015), Mycelium supports BIP 70 payment protocol

See the attached screenshot from a transaction I just did. Using our support utilities I can also confirm that the wallet is also sending a refund address with the transaction.

Would be good to also included in the list of wallet supporting the payment protocol on our website - https://bitpay.com/docs/wallets

![mycelium_bip70](https://cloud.githubusercontent.com/assets/12460881/8112167/64aea08a-1066-11e5-8009-069e0e036086.png)

**Comment by bitjson** [comment]
Excellent, updated here: https://github.com/bitpay/bitpay-website/commit/28157e285cf0f8d7e8d346577cf527897e4f3a80

Thanks!
